# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
target 'mitugou' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  # Pods for mitugou
  # 导入网络框架请求
  pod 'AFNetworking'
   # 网络监控
  pod 'Reachability'
  # 字典转模型
  pod 'MJExtension'
  # 下拉刷新
  pod 'MJRefresh'
  # 图片加载
  pod 'SDWebImage'
  # 用于适配
  pod 'Masonry'
  # 蒙版
  pod 'SVProgressHUD'
  # 轮播
  pod 'SDCycleScrollView'
  # 全局滚动
  pod 'FDFullscreenPopGesture'
  # #bugtags
  pod 'Bugtags'  
  #导入提示框
  pod 'MBProgressHUD'
  #导入massory
  pod 'Masonry'
end
